#!/usr/bin/env sh
DIR=$(dirname $0)
JAVA_VER=$(java -version 2>&1 | sed 's/java version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q')
if [[ $JAVA_VER < 18 ]] ; then
    echo "Needs at least java 8 (current: `(java -version 2>&1 | head -1)`)"
    exit 1
fi
java -jar $DIR/mihxil-json-formatter-${project.version}-executable.jar "$@"
