---
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        gpg-passphrase: GPG_SECRET_KEY_PASSPHRASE
    - name: Build with Maven
      run: mvn -B -fae
    - uses: codecov/codecov-action@v2
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.1.0
      if: (success() || failure())
      with:
        junit_files: "**/target/surefire-reports/*.xml"
    - name: Deploy with Maven
      run: mvn -B -Pdeploy  -DskipTests=true  deploy
      if: ${{ github.event_name == 'push' }}
      env:
        SONATYPE_USERNAME: mihxil
        SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_SECRET_KEY_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}

