---
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            target: 'deploy'
          - os: ubuntu-latest
            java: 21
            target: 'test'
          - os: ubuntu-latest
            java: 25
            target: 'test'
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
    - name: Build with Maven
      run: mvn -B -fae ${{ matrix.target }}
    - uses: codecov/codecov-action@v5
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (success() || failure())
      with:
        files: "**/target/surefire-reports/*.xml"
    - name: Deploy with Maven
      run: mvn -B -Pdeploy  -DskipTests=true  deploy
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
    - name: Run benchmarks
      run: |
        java -jar  mihxil-json-benchmarks/target/benchmarks.jar   -wi 1 -i 3 -f 1 -rf json | tee output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
          tool: 'jmh'
          output-file-path: jmh-result.json
          alert-threshold: '200%'
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: false
